### PR TITLE
MPI Variants

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by dalcinl** [comment]
@minrk Just look at this beautiful macOS failure! I have better things in my life that fighting CMake if I have an alternative. Can I switch to a standard `./configure && make && make install` build?

**Comment by dalcinl** [comment]
@minrk I cannot reproduce the failure in my macOS 10.13.5 system. How should I proceed? Do you have any CMake hack to suggest?

**Comment by minrk** [comment]
Seems we ran into [this bug](https://gitlab.kitware.com/cmake/cmake/merge_requests/1952), which will be released in cmake 3.12. Setting CC/CXX to mpi compilers explicitly appears to fix it.

**Comment by dalcinl** [comment]
@minrk Please merge.

**Pull request merged**
