### PR TITLE
Arch: Add aarch64 and ppc64le

### PR DESCRIPTION
**Pull request by ax3l**
Add builds for these new platforms.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

License Change: Apache 2.0
See https://github.com/hypre-space/hypre/blob/v2.18.2/COPYRIGHT

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@conda-forge/hypre This is ready for merge, please be aware that License was updated, check that it is correct.

**Comment by ax3l** [comment]
Thanks!
Just to link the license update again: https://github.com/hypre-space/hypre/blob/v2.18.2/COPYRIGHT

**Comment by ax3l** [comment]
ping @minrk @dalcinl @SylvainCorlay @davidbrochart: `hypre` arch migration to `ppc64le` & `aarch64` is ready for merge :) 

Updated license to reflect [upstream change to Apache 2.0](https://github.com/hypre-space/hypre/blob/v2.18.2/COPYRIGHT).

**Pull request merged**
